### ISSUE TITLE
How make the map show streets and not the satelite images ?

### ISSUE THREAD

**Issue by fukhaos** [jozefchutka/YCanvas#2]
I using the map for Starling/Feathers.

**Comment by jozefchutka** [comment]
hello Fukhaos,

in order to change map provider, have a look at Partition.as. This class is responsible for converting x, y, z (level) into url request. You can see it in use in ApplicationMap or ApplicationExplorer. 
As for the tile map provider you can use openstreetmaps, mapbox, cloudmade, bing tiles or anything else as long as the server provides proper crossdomain.xml
