### ISSUE TITLE
Integration of Google Map

### ISSUE THREAD

**Issue by santanu4ver** [jozefchutka/YCanvas#4]
Hi,

Is it possible to integrate Google Map in the map list? I was also in need to showing route - but I have a very little knowledge map API.

Thanks!

**Comment by jozefchutka** [comment]
hi Santanu,

this question is very common. here is the answer from faq that was available on my blog:
Q: Can you run google maps?
A: Technicaly yes, on AIR there is no problem at all. In case of Flash Player, however, engine uploads BitmapData to graphic cards, in order to upload it you need the access that would be granted via crossdomain.xml, and unfortunately google maps domains do not serve one.

and some of my private answers via email:
ycanvas is a tile renderer and its up to you how you translate x,y,z coordinates to url. the reference implementations you can find in repository (see ApplicationMap folder) loads tiles from opensourcemaps, arcgis, mapquest, mapbox, bing maps. You can start from there and update tile requests to target google tiles. To get tiles from google maps might be a little bit tricky, afaik their latest version is partialy rendered from vectors on client side. anyway, they still have the pure tile based version. The easiest way to get tile url is monitor traffic in some original google map example (fiddler, charlesproxy, chrome dev tools...). you can spot the x,y,z parameter in there. Make also sure to follow google ToS for using these tiles, if that does not fit you, you can still use any of these open alternatives (osm, mapquest...)

one more:
I believe there are some restrictions and additional policies on google maps. AFAIK google provides only javascript maps implementation and no more flash. Also their latest implementation is vector based not tile based which means they send structured data and render partially on client side. There are some other possibilities where you can take tiles from: openstreetmap, mapquest, bing maps...

you can start implementing your google partition into ApplicationExplorer via [GoogleMapsPartition.as](https://github.com/jozefchutka/YCanvas/blob/master/ApplicationExplorer/src/main/actionscript/sk/yoz/ycanvas/demo/explorer/modes/googlemaps/GoogleMapsPartition.as),
have inspiration from [MapQuestPartition.as](https://github.com/jozefchutka/YCanvas/blob/master/ApplicationExplorer/src/main/actionscript/sk/yoz/ycanvas/demo/explorer/modes/mapquest/MapQuestPartition.as) while providing tile urls from google. [this example](https://developers.google.com/maps/documentation/javascript/examples/map-simple) here seems to use tiles. requests it makes:

```
https://mts0.googleapis.com/vt?lyrs=m@258034207&src=apiv3&hl=en-US&x=940&y=616&z=10&style=47,37%7Csmartmaps
https://mts1.googleapis.com/vt?lyrs=m@258092945&src=apiv3&hl=en-US&x=939&y=616&z=10&style=47,37%7Csmartmaps
```

regarding path search, I do not know about any free service with sufficient stability or TOS. you might want to look for commercial solutions or run your own openstreetmap database which would let you do much more magic...

**Comment by santanu4ver** [comment]
Hi Jozef,

That is a quite lot for me to start with in this subject. Thank you. 

Also, is YCanvasMap has ability to user location update? Or, this is something which requires ANE.

Thanks!

Regards,
Santanu

**Comment by santanu4ver** [comment]
I noticed the route points for New York to Washington or Rome to Paris are hardcoded. How you get them? Is there any service/API to query those values? Thanks!

**Comment by jozefchutka** [comment]
for current location of your device you should can use [Geolocation class](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/sensors/Geolocation.html)

route points in map were taken from openrouteservice, [other online routing services can be found here](http://wiki.openstreetmap.org/wiki/Routing/online_routers)
